# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x04\x63ore\"\xa1\x01\n\x0fSetStateRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x39\n\nattributes\x18\x03 \x03(\x0b\x32%.core.SetStateRequest.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\x10SetStateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"$\n\x0fGetStateRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\"\xc8\x01\n\x10GetStateResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12:\n\nattributes\x18\x04 \x03(\x0b\x32&.core.GetStateResponse.AttributesEntry\x12\x14\n\x0clast_updated\x18\x05 \x01(\x03\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x12\n\x10GetConfigRequest\"u\n\x11GetConfigResponse\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\televation\x18\x03 \x01(\x01\x12\x11\n\ttime_zone\x18\x04 \x01(\t\x12\x15\n\rlocation_name\x18\x05 \x01(\t2\xc1\x01\n\x0b\x43oreService\x12\x39\n\x08SetState\x12\x15.core.SetStateRequest\x1a\x16.core.SetStateResponse\x12\x39\n\x08GetState\x12\x15.core.GetStateRequest\x1a\x16.core.GetStateResponse\x12<\n\tGetConfig\x12\x16.core.GetConfigRequest\x1a\x17.core.GetConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETSTATEREQUEST_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_SETSTATEREQUEST_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_GETSTATERESPONSE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_GETSTATERESPONSE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SETSTATEREQUEST']._serialized_start=21
  _globals['_SETSTATEREQUEST']._serialized_end=182
  _globals['_SETSTATEREQUEST_ATTRIBUTESENTRY']._serialized_start=133
  _globals['_SETSTATEREQUEST_ATTRIBUTESENTRY']._serialized_end=182
  _globals['_SETSTATERESPONSE']._serialized_start=184
  _globals['_SETSTATERESPONSE']._serialized_end=234
  _globals['_GETSTATEREQUEST']._serialized_start=236
  _globals['_GETSTATEREQUEST']._serialized_end=272
  _globals['_GETSTATERESPONSE']._serialized_start=275
  _globals['_GETSTATERESPONSE']._serialized_end=475
  _globals['_GETSTATERESPONSE_ATTRIBUTESENTRY']._serialized_start=133
  _globals['_GETSTATERESPONSE_ATTRIBUTESENTRY']._serialized_end=182
  _globals['_GETCONFIGREQUEST']._serialized_start=477
  _globals['_GETCONFIGREQUEST']._serialized_end=495
  _globals['_GETCONFIGRESPONSE']._serialized_start=497
  _globals['_GETCONFIGRESPONSE']._serialized_end=614
  _globals['_CORESERVICE']._serialized_start=617
  _globals['_CORESERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
