# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from homeassistant.grpc import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetState = channel.unary_unary(
                '/core.CoreService/SetState',
                request_serializer=core__pb2.SetStateRequest.SerializeToString,
                response_deserializer=core__pb2.SetStateResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/core.CoreService/GetState',
                request_serializer=core__pb2.GetStateRequest.SerializeToString,
                response_deserializer=core__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/core.CoreService/GetConfig',
                request_serializer=core__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=core__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.GetIntegrationConfig = channel.unary_unary(
                '/core.CoreService/GetIntegrationConfig',
                request_serializer=core__pb2.GetIntegrationConfigRequest.SerializeToString,
                response_deserializer=core__pb2.GetIntegrationConfigResponse.FromString,
                _registered_method=True)
        self.RegisterIntegration = channel.unary_unary(
                '/core.CoreService/RegisterIntegration',
                request_serializer=core__pb2.RegisterIntegrationRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterIntegrationResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrationConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=core__pb2.SetStateRequest.FromString,
                    response_serializer=core__pb2.SetStateResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=core__pb2.GetStateRequest.FromString,
                    response_serializer=core__pb2.GetStateResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=core__pb2.GetConfigRequest.FromString,
                    response_serializer=core__pb2.GetConfigResponse.SerializeToString,
            ),
            'GetIntegrationConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrationConfig,
                    request_deserializer=core__pb2.GetIntegrationConfigRequest.FromString,
                    response_serializer=core__pb2.GetIntegrationConfigResponse.SerializeToString,
            ),
            'RegisterIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterIntegration,
                    request_deserializer=core__pb2.RegisterIntegrationRequest.FromString,
                    response_serializer=core__pb2.RegisterIntegrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreService/SetState',
            core__pb2.SetStateRequest.SerializeToString,
            core__pb2.SetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreService/GetState',
            core__pb2.GetStateRequest.SerializeToString,
            core__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreService/GetConfig',
            core__pb2.GetConfigRequest.SerializeToString,
            core__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrationConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreService/GetIntegrationConfig',
            core__pb2.GetIntegrationConfigRequest.SerializeToString,
            core__pb2.GetIntegrationConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.CoreService/RegisterIntegration',
            core__pb2.RegisterIntegrationRequest.SerializeToString,
            core__pb2.RegisterIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
