"""Constants for the horizontal_scaling component."""

from homeassistant.worker.const import (
    DATA_WORKER_REGISTRY,
    WORKER_STATUS_NOT_IMPLEMENTED,
    WORKER_STATUS_RUNNING,
    WORKER_STATUS_STARTING,
    WORKER_STATUS_UNAVAILABLE,
    WORKER_TYPE_DOCKER,
    WORKER_TYPE_KUBERNETES,
    WORKER_TYPE_PROCESS,
    WORKER_TYPE_REMOTE,
)

__all__ = [
    "DATA_WORKER_REGISTRY",
    "WORKER_STATUS_NOT_IMPLEMENTED",
    "WORKER_STATUS_RUNNING",
    "WORKER_STATUS_STARTING",
    "WORKER_STATUS_UNAVAILABLE",
    "WORKER_TYPE_DOCKER",
    "WORKER_TYPE_KUBERNETES",
    "WORKER_TYPE_PROCESS",
    "WORKER_TYPE_REMOTE",
    # Configuration keys (component-specific)
    "CONF_WORKERS",
    "CONF_WORKER_NAME",
    "CONF_WORKER_TYPE",
    "CONF_WORKER_PORT",
    "CONF_WORKER_MAX_INTEGRATIONS",
    "CONF_WORKER_ADDRESS",
    "CONF_WORKER_IMAGE",
    "CONF_WORKER_HOST",
    "CONF_WORKER_NAMESPACE",
    "CONF_WORKER_POD_SPEC",
    "CONF_WORKER_RESOURCES",
    "CONF_WORKER_RESOURCES_CPU",
    "CONF_WORKER_RESOURCES_MEMORY",
    "CONF_WORKER_RESOURCES_CPU_SHARES",
    "CONF_WORKER_STOP_ON_SHUTDOWN",
    "DOMAIN",
]

DOMAIN = "horizontal_scaling"

# Configuration keys
CONF_WORKERS = "workers"
CONF_WORKER_NAME = "name"
CONF_WORKER_TYPE = "type"
CONF_WORKER_PORT = "port"
CONF_WORKER_MAX_INTEGRATIONS = "max_integrations"
CONF_WORKER_ADDRESS = "address"
CONF_WORKER_IMAGE = "image"
CONF_WORKER_HOST = "host"
CONF_WORKER_NAMESPACE = "namespace"
CONF_WORKER_POD_SPEC = "pod_spec"
CONF_WORKER_RESOURCES = "resources"
CONF_WORKER_RESOURCES_CPU = "cpu"
CONF_WORKER_RESOURCES_MEMORY = "memory"
CONF_WORKER_RESOURCES_CPU_SHARES = "cpu_shares"
CONF_WORKER_STOP_ON_SHUTDOWN = "stop_on_shutdown"
