# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from homeassistant.core_grpc.protos import core_pb2 as core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetState = channel.unary_unary(
                '/homeassistant.core.CoreService/SetState',
                request_serializer=core__pb2.SetStateRequest.SerializeToString,
                response_deserializer=core__pb2.SetStateResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/homeassistant.core.CoreService/GetState',
                request_serializer=core__pb2.GetStateRequest.SerializeToString,
                response_deserializer=core__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.RegisterService = channel.unary_unary(
                '/homeassistant.core.CoreService/RegisterService',
                request_serializer=core__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.CallServiceOnRemote = channel.unary_unary(
                '/homeassistant.core.CoreService/CallServiceOnRemote',
                request_serializer=core__pb2.CallServiceOnRemoteRequest.SerializeToString,
                response_deserializer=core__pb2.CallServiceOnRemoteResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/homeassistant.core.CoreService/RegisterWorker',
                request_serializer=core__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=core__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.GetEntry = channel.unary_unary(
                '/homeassistant.core.CoreService/GetEntry',
                request_serializer=core__pb2.GetEntryRequest.SerializeToString,
                response_deserializer=core__pb2.GetEntryResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/homeassistant.core.CoreService/GetConfig',
                request_serializer=core__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=core__pb2.GetConfigResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallServiceOnRemote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=core__pb2.SetStateRequest.FromString,
                    response_serializer=core__pb2.SetStateResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=core__pb2.GetStateRequest.FromString,
                    response_serializer=core__pb2.GetStateResponse.SerializeToString,
            ),
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=core__pb2.RegisterServiceRequest.FromString,
                    response_serializer=core__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'CallServiceOnRemote': grpc.unary_unary_rpc_method_handler(
                    servicer.CallServiceOnRemote,
                    request_deserializer=core__pb2.CallServiceOnRemoteRequest.FromString,
                    response_serializer=core__pb2.CallServiceOnRemoteResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=core__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=core__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'GetEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntry,
                    request_deserializer=core__pb2.GetEntryRequest.FromString,
                    response_serializer=core__pb2.GetEntryResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=core__pb2.GetConfigRequest.FromString,
                    response_serializer=core__pb2.GetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'homeassistant.core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('homeassistant.core.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/SetState',
            core__pb2.SetStateRequest.SerializeToString,
            core__pb2.SetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/GetState',
            core__pb2.GetStateRequest.SerializeToString,
            core__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/RegisterService',
            core__pb2.RegisterServiceRequest.SerializeToString,
            core__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallServiceOnRemote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/CallServiceOnRemote',
            core__pb2.CallServiceOnRemoteRequest.SerializeToString,
            core__pb2.CallServiceOnRemoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/RegisterWorker',
            core__pb2.RegisterWorkerRequest.SerializeToString,
            core__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/GetEntry',
            core__pb2.GetEntryRequest.SerializeToString,
            core__pb2.GetEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.CoreService/GetConfig',
            core__pb2.GetConfigRequest.SerializeToString,
            core__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallService = channel.unary_unary(
                '/homeassistant.core.WorkerService/CallService',
                request_serializer=core__pb2.WorkerCallServiceRequest.SerializeToString,
                response_deserializer=core__pb2.WorkerCallServiceResponse.FromString,
                _registered_method=True)
        self.SetupEntry = channel.unary_unary(
                '/homeassistant.core.WorkerService/SetupEntry',
                request_serializer=core__pb2.WorkerSetupEntryRequest.SerializeToString,
                response_deserializer=core__pb2.WorkerSetupEntryResponse.FromString,
                _registered_method=True)
        self.TeardownEntry = channel.unary_unary(
                '/homeassistant.core.WorkerService/TeardownEntry',
                request_serializer=core__pb2.WorkerTeardownEntryRequest.SerializeToString,
                response_deserializer=core__pb2.WorkerTeardownEntryResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeardownEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallService': grpc.unary_unary_rpc_method_handler(
                    servicer.CallService,
                    request_deserializer=core__pb2.WorkerCallServiceRequest.FromString,
                    response_serializer=core__pb2.WorkerCallServiceResponse.SerializeToString,
            ),
            'SetupEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupEntry,
                    request_deserializer=core__pb2.WorkerSetupEntryRequest.FromString,
                    response_serializer=core__pb2.WorkerSetupEntryResponse.SerializeToString,
            ),
            'TeardownEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.TeardownEntry,
                    request_deserializer=core__pb2.WorkerTeardownEntryRequest.FromString,
                    response_serializer=core__pb2.WorkerTeardownEntryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'homeassistant.core.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('homeassistant.core.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.WorkerService/CallService',
            core__pb2.WorkerCallServiceRequest.SerializeToString,
            core__pb2.WorkerCallServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetupEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.WorkerService/SetupEntry',
            core__pb2.WorkerSetupEntryRequest.SerializeToString,
            core__pb2.WorkerSetupEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeardownEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homeassistant.core.WorkerService/TeardownEntry',
            core__pb2.WorkerTeardownEntryRequest.SerializeToString,
            core__pb2.WorkerTeardownEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
