# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: integration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'integration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11integration.proto\x12\x0bintegration\"\x8a\x01\n\x0bInitRequest\x12\x16\n\x0eintegration_id\x18\x01 \x01(\t\x12\x34\n\x06\x63onfig\x18\x02 \x03(\x0b\x32$.integration.InitRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"B\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nentity_ids\x18\x03 \x03(\t\"&\n\x0cStartRequest\x12\x16\n\x0eintegration_id\x18\x01 \x01(\t\"/\n\rStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"%\n\x0bStopRequest\x12\x16\n\x0eintegration_id\x18\x01 \x01(\t\"\x1f\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xb6\x01\n\x12\x43\x61llServiceRequest\x12\x16\n\x0eintegration_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x37\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32).integration.CallServiceRequest.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"5\n\x13\x43\x61llServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa6\x02\n\x12IntegrationService\x12\x41\n\nInitialize\x12\x18.integration.InitRequest\x1a\x19.integration.InitResponse\x12>\n\x05Start\x12\x19.integration.StartRequest\x1a\x1a.integration.StartResponse\x12;\n\x04Stop\x12\x18.integration.StopRequest\x1a\x19.integration.StopResponse\x12P\n\x0b\x43\x61llService\x12\x1f.integration.CallServiceRequest\x1a .integration.CallServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'integration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_INITREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_CALLSERVICEREQUEST_DATAENTRY']._loaded_options = None
  _globals['_CALLSERVICEREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_INITREQUEST']._serialized_start=35
  _globals['_INITREQUEST']._serialized_end=173
  _globals['_INITREQUEST_CONFIGENTRY']._serialized_start=128
  _globals['_INITREQUEST_CONFIGENTRY']._serialized_end=173
  _globals['_INITRESPONSE']._serialized_start=175
  _globals['_INITRESPONSE']._serialized_end=241
  _globals['_STARTREQUEST']._serialized_start=243
  _globals['_STARTREQUEST']._serialized_end=281
  _globals['_STARTRESPONSE']._serialized_start=283
  _globals['_STARTRESPONSE']._serialized_end=330
  _globals['_STOPREQUEST']._serialized_start=332
  _globals['_STOPREQUEST']._serialized_end=369
  _globals['_STOPRESPONSE']._serialized_start=371
  _globals['_STOPRESPONSE']._serialized_end=402
  _globals['_CALLSERVICEREQUEST']._serialized_start=405
  _globals['_CALLSERVICEREQUEST']._serialized_end=587
  _globals['_CALLSERVICEREQUEST_DATAENTRY']._serialized_start=544
  _globals['_CALLSERVICEREQUEST_DATAENTRY']._serialized_end=587
  _globals['_CALLSERVICERESPONSE']._serialized_start=589
  _globals['_CALLSERVICERESPONSE']._serialized_end=642
  _globals['_INTEGRATIONSERVICE']._serialized_start=645
  _globals['_INTEGRATIONSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
